on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push (Master)
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          fetch-depth: 0

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: npm install
        run: npm install

      - name: Fast FTP Action
        uses: anvil-solutions/Fast-FTP-Action@2.1.3
        with:
          server: listouve-api.junio.cc
          port: 22
          username: listouve@listouve-api.junio.cc
          password: ${{ secrets.FTP_PASS }}
#      - name: "Deploy"
#        uses: milanmk/actions-file-deployer@master
#        with:
#          remote-protocol: "sftp"
#          remote-host: "listouve-api.junio.cc"
#          remote-user: "listouve@listouve-api.junio.cc"
#          remote-password:  ${{ secrets.FTP_PASS }}
#          ssh-private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
#          remote-path: "/var/www/example.com"

      # - name: npm run production
      # #   run: npm run production
      # - name: Teste Junio
      #   run: echo "${{ FTP_HOST }}"
      #   env:
      #     FTP_HOST: ${{ env.FTP_HOST }}
#      - name: 📂 Sync files
#        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
#        with:
#          ftp_host: listouve-api.junio.cc
#          ftp_username: listouve@listouve-api.junio.cc
#          ftp_password: ${{ secrets.FTP_PASS }}
##          only_newer: true
#          # local_source_dir: "dist"
#          # dist_target_dir: "www/my-app"
##          delete: "true"
#          exclude: "'^logs/' '^README.md' '^node_modules'"
      # - name: 📂 Sync files
      #   uses: locaweb/ftp-deploy@1.0.0
      #   with:
      #     # ftp-server: listouve-api.junio.cc
      #     # ftp-username: listouve-api@listouve-api.junio.cc
      #     # ftp-password: ${{ secrets.FTP_PASS }}
      #     host: listouve-api.junio.cc
      #     user: listouve-api@listouve-api.junio.cc
      #     password: ${{ secrets.FTP_PASS }}
      #     # localDir: "dist"
      #     # server-dir: public_html/
#      - name: FTP Deployer
#        uses: sand4rt/ftp-deployer@v1.7
#        with:
#          sftp: false # optional
#          host: listouve-api.junio.cc # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
#          port: 21 # optional, default is: 21
#          username: listouve@listouve-api.junio.cc # FTP username
#          password: ${{ secrets.FTP_PASS }} # FTP password
#          remote_folder: ${{ secrets.FTP_REMOTE_FOLDER }} # optional, remote path of your FTP server
#          local_folder: dist # optional, local path, default is: dist
#          cleanup: false # optional, remove existing files inside FTP remote folder
#          include: '[]' # optional, e.g. '['dist']'
#          exclude: '[]' # optional,  e.g. '['node_modules/**', '.git/**', '*.env']'
#          passive: true # optional
