on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push (Master)
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: npm install
        run: npm install
      
      # - name: npm run production
      # #   run: npm run production
      # - name: Teste Junio
      #   run: echo "${{ FTP_HOST }}" 
      #   env:
      #     FTP_HOST: ${{ env.FTP_HOST }}
  
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: listouve-api.junio.cc
          username: listouve-api@listouve-api.junio.cc
          password: ${{ secrets.FTP_PASS }}
          # server-dir: public_html/
